apiVersion: v1
kind: Service
metadata: 
  name: drupal-mysql-service
  labels:
    app: drupal
spec: 
  type: ClusterIP
  selector:
    app: drupal
  ports:
  - port: 3306
    targetPort: 3306

  





