apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service
  namespace: default
  labels:
    app: redis-cluster
spec:
  ports:
  - port: 6379  
    targetPort: 6379
    name: client
  - port: 16379
    name:  gossip
    targetPort: 16379
  selector:
    app: redis