apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: vote
  labels:
    app: vote-app
spec:
  type: NodePort
  selector:
    app: vote-app
  ports:
    - port: 5000
      targetPort: 80
      nodePort: 31000

  