apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  labels: 
    app: file-server
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem 
  hostPath:
    path: /web
