apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels:
    app: file-server
spec:
      containers:
        - name: fileserver
          image: kodekloud/fileserver
          volumeMounts:
          - name: data-store
            mountPath: "/web"
      volumes:
      - name: data-store
        persistentVolumeClaim:
          claimName: data-pvc
 

