apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
  labels:
    app: file-server
spec:
  type: NodePort
  selector:
    app: file-server
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31200
