#jekyll kubernetes deployment

apiVersion: apps/v1
kind: Pod
metadata:
  name: jekyll
  labels:
    run: jekyll
  namespace: development
spec:
  initContainers:
    - name: copy-jekyll-site
      image: kodekloud/jekyll
      command: ["jekyll", "new", "/site"]
      volumeMounts:
        - name: site
          mountPath: /site
  containers:
      - image: kodekloud/jekyll-serve
        name: jekyll
        volumeMounts:
          - name: site
            mountPath: /site
  volumes:
      - name: site
        persistentVolumeClaim:
          claimName: jekyll-site
