apiVersion: v1
kind: PersistentVolume
metadata:
  name: jekyll-site
spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 1Gi
    hostPath:
      path: /site
      type: ""
    persistentVolumeReclaimPolicy: Retain
    volumeMode: Filesystem

