apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  jekyll-site
  namespace: development
  labels:
    run: jekyll
spec:
  accessModes:
    - ReadWriteMany
  resources:  
    requests:
      storage: 1Gi
  volumeName: jekyll-site